# Generated by Django 4.2.16 on 2024-12-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_alter_bid_id_alter_comment_id_alter_listing_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="currentBid",
            field=models.DecimalField(
                decimal_places=2, default=0.0, help_text="In Rupees (₹)", max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="image",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
